// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import "./interfaces/IVaultStrategy.sol";

/**
 * @title SimAaveV3Strategy
 * @notice Simulates Aave V3 USDC supply market on Arbitrum.
 *
 * ── Interest-rate model ────────────────────────────────────────────────────
 * Mirrors Aave V3 DefaultReserveInterestRateStrategy (two-slope linear model):
 *
 *   util ≤ OPTIMAL:  supplyAPY = SLOPE1 × util / OPTIMAL
 *   util >  OPTIMAL:  supplyAPY = SLOPE1 + SLOPE2 × (util − OPTIMAL) / (1 − OPTIMAL)
 *
 * Calibrated to real Arbitrum Sepolia USDC market (as of early 2025):
 *   SLOPE1   =  7%  (700 bps)   — "normal" demand region
 *   SLOPE2   = 75%  (7500 bps)  — "stress" region above optimal
 *   OPTIMAL  = 80%  (8000 bps)  — kink point
 *
 * Representative operating points
 *   util 45% → APY  3.9%   (low-demand bear market)
 *   util 65% → APY  5.7%   (normal market, default)
 *   util 80% → APY  7.0%   (high demand)
 *   util 95% → APY 18.6%  (near-liquidation crisis)
 *
 * ── Yield generation ───────────────────────────────────────────────────────
 * Yield is generated by calling MockUSDC.mint() — no reserve needed.
 * This accurately models a lending protocol: principal is lent to borrowers
 * who pay interest; the protocol mints the interest income to LPs (suppliers).
 * On mainnet this would be replaced by real aToken interest accrual.
 *
 * ── Access control ─────────────────────────────────────────────────────────
 *   owner (= StrategyRouter) — deposit / withdraw / harvest
 *   marketAdmin              — setUtilization (simulate demand shifts)
 */
contract SimAaveV3Strategy is IVaultStrategy, Ownable, ReentrancyGuard {
    using SafeERC20 for IERC20;

    // ─── Aave V3 USDC rate model (Arbitrum, 2025) ─────────────────────────────

    uint256 public constant SLOPE1_BPS  =  700;   // 7%  below optimal
    uint256 public constant SLOPE2_BPS  = 7500;   // 75% above optimal
    uint256 public constant OPTIMAL_BPS = 8000;   // 80% optimal utilization

    // ─── Market state ─────────────────────────────────────────────────────────

    /// @notice Simulated pool utilization (0–10000 bps). Reflects real Aave V3 util.
    uint256 public utilizationBps = 6500; // 65% → 5.7% APY (normal market default)

    /// @notice Address that can update market parameters (deployer / demo keeper).
    address public marketAdmin;

    // ─── Accounting ───────────────────────────────────────────────────────────

    IERC20  public immutable usdc;
    uint256 public deployedPrincipal;
    uint256 public lastAccrualTime;
    uint256 public accruedYield;
    bool    public paused;

    // ─── Events ───────────────────────────────────────────────────────────────

    event UtilizationUpdated(uint256 oldBps, uint256 newBps, uint256 impliedApyBps);
    event Deposited(uint256 amount, uint256 newPrincipal);
    event Withdrawn(uint256 amount, uint256 newPrincipal);
    event Harvested(uint256 yieldAmount, uint256 apyBps_);
    event YieldAccrued(uint256 amount, uint256 elapsed);
    event MarketAdminChanged(address indexed oldAdmin, address indexed newAdmin);

    // ─── Constructor ──────────────────────────────────────────────────────────

    /**
     * @param _usdc        MockUSDC address (must implement mint())
     * @param _marketAdmin Address that can update utilization (deployer)
     * @param _owner       Initial owner — transfer to StrategyRouter after deploy
     */
    constructor(address _usdc, address _marketAdmin, address _owner) Ownable(_owner) {
        require(_usdc != address(0),        "SA3: zero usdc");
        require(_marketAdmin != address(0), "SA3: zero admin");
        usdc          = IERC20(_usdc);
        marketAdmin   = _marketAdmin;
        lastAccrualTime = block.timestamp;
    }

    // ─── IVaultStrategy ───────────────────────────────────────────────────────

    function asset() external view override returns (address) {
        return address(usdc);
    }

    function deposit(uint256 amount) external override onlyOwner nonReentrant {
        require(!paused,    "SA3: paused");
        require(amount > 0, "SA3: zero amount");
        _accrueYield();
        usdc.safeTransferFrom(msg.sender, address(this), amount);
        deployedPrincipal += amount;
        emit Deposited(amount, deployedPrincipal);
    }

    function withdraw(uint256 amount) external override onlyOwner nonReentrant {
        require(amount > 0,                   "SA3: zero amount");
        require(deployedPrincipal >= amount,  "SA3: insufficient principal");
        _accrueYield();
        deployedPrincipal -= amount;
        usdc.safeTransfer(msg.sender, amount);
        emit Withdrawn(amount, deployedPrincipal);
    }

    /**
     * @notice Harvest yield accrued since last harvest.
     *         Mints USDC directly (models Aave aToken interest), no reserve needed.
     */
    function harvest() external override onlyOwner nonReentrant returns (uint256 yieldAmount) {
        _accrueYield();
        yieldAmount  = accruedYield;
        if (yieldAmount == 0) return 0;
        accruedYield = 0;
        IMintableToken(address(usdc)).mint(msg.sender, yieldAmount);
        emit Harvested(yieldAmount, apyBps());
    }

    /// @notice Principal + pending accrued yield (reflects economic value of position).
    function totalAssets() external view override returns (uint256) {
        return deployedPrincipal + accruedYield + _pendingYield();
    }

    // ─── APY model ────────────────────────────────────────────────────────────

    /**
     * @notice Current supply APY derived from utilization.
     *         Matches Aave V3's two-slope interest rate model exactly.
     */
    function apyBps() public view returns (uint256) {
        uint256 util = utilizationBps;
        if (util <= OPTIMAL_BPS) {
            // Linear slope below kink
            return (SLOPE1_BPS * util) / OPTIMAL_BPS;
        }
        // Jump-rate above kink
        uint256 excess = util - OPTIMAL_BPS;
        return SLOPE1_BPS + (SLOPE2_BPS * excess) / (10_000 - OPTIMAL_BPS);
    }

    // ─── Market simulation ────────────────────────────────────────────────────

    /**
     * @notice Update pool utilization to simulate real-world demand shifts.
     *
     * Example market scenarios:
     *   Low-demand bear:  setUtilization(4500) → APY 3.9%
     *   Normal market:    setUtilization(6500) → APY 5.7%  (default)
     *   High demand:      setUtilization(8000) → APY 7.0%
     *   Stress event:     setUtilization(9500) → APY 18.6%
     *
     * Only callable by marketAdmin (deployer / demo keeper), not vault flow.
     */
    function setUtilization(uint256 _bps) external {
        require(msg.sender == marketAdmin, "SA3: not market admin");
        require(_bps <= 10_000,            "SA3: invalid utilization");
        emit UtilizationUpdated(utilizationBps, _bps, apyBps());
        // Accrue at old rate before switching
        _accrueYield();
        utilizationBps = _bps;
        emit UtilizationUpdated(_bps, _bps, apyBps());
    }

    function setMarketAdmin(address _admin) external {
        require(msg.sender == marketAdmin, "SA3: not market admin");
        emit MarketAdminChanged(marketAdmin, _admin);
        marketAdmin = _admin;
    }

    // ─── Owner admin ──────────────────────────────────────────────────────────

    function setPaused(bool _paused) external onlyOwner {
        paused = _paused;
    }

    function simulateLoss(uint256 lossAmount) external onlyOwner {
        require(lossAmount > 0,                  "SA3: zero loss");
        require(lossAmount <= deployedPrincipal, "SA3: exceeds principal");
        deployedPrincipal -= lossAmount;
    }

    // ─── Views ────────────────────────────────────────────────────────────────

    /// @notice Human-readable description of current market state.
    function marketState() external view returns (
        uint256 utilization,
        uint256 supplyApy,
        uint256 principal,
        uint256 pending
    ) {
        return (utilizationBps, apyBps(), deployedPrincipal, _pendingYield());
    }

    // ─── Internal ─────────────────────────────────────────────────────────────

    function _accrueYield() internal {
        uint256 pending = _pendingYield();
        if (pending > 0) {
            accruedYield += pending;
            emit YieldAccrued(pending, block.timestamp - lastAccrualTime);
        }
        lastAccrualTime = block.timestamp;
    }

    function _pendingYield() internal view returns (uint256) {
        if (deployedPrincipal == 0) return 0;
        uint256 elapsed = block.timestamp - lastAccrualTime;
        if (elapsed == 0) return 0;
        return (deployedPrincipal * apyBps() * elapsed) / (365 days * 10_000);
    }
}
